name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.2

      - name: lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61

      - name: build
        run: |
          make setup
          make build
